//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pago.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public System.Guid ID_Log { get; set; }
        public string Sistema { get; set; }
        public string Accion { get; set; }
        public string Patente { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
